Single job app detail
cse110-fa22-group24/cse110-fa22-group24 pull request #28
Opened 2022-11-13 11:53 UTC by Lemin-Jin

I have added some style to match the hifi. I haven't build the tag yet

2022-11-13 22:25 UTC, ZhuoyangM approved these changes
Looks good!

2022-11-14 20:44 UTC, JessalynWang requested changes
Should we have some sort of file hierarchy for custom HTMLElements? Not exactly sure what yet but I think it will be confusing to have all of the html files in once place as this project grows

2022-11-14 21:00 UTC, PierreBeur commented
Good idea, we can relocate `job-details.html` into `source/reference`

2022-11-15 04:40 UTC, JessalynWang approved these changes

2022-11-15 04:40 UTC, merged